<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLWW1nEd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLWW1nEd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLWW1nEd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLWW1nEd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLWW1nEd\App_KernelDevDebugContainer([
    'container.build_hash' => 'LWW1nEd',
    'container.build_id' => 'bab38eb6',
    'container.build_time' => 1710498658,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLWW1nEd');
