<?php

namespace ContainerNTdBb2m;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__B4k9WgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..B4k9Wg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..B4k9Wg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mov' => ['privates', '.errored..service_locator..B4k9Wg.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator..B4k9Wg": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'mov' => 'App\\Entity\\Category',
            'serializer' => '?',
        ]);
    }
}
