<?php

namespace ContainerNTdBb2m;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Wql8jrV.App\Entity\Movie' shared service.
     *
     * @return \App\Entity\Movie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Wql8jrV": it needs an instance of "App\\Entity\\Movie" but this type has been excluded in "config/services.yaml".');
    }
}
